#!/bin/sh

CFLAGS="-D__MACOSX__ -arch ppc -arch i386" CXXFLAGS="-D__MACOSX__ -arch i386 -arch ppc"  LDFLAGS="-arch i386 -arch ppc" ./configure --disable-dependency-tracking --prefix=`pwd`"/FreeDroid.app/Contents/Resources/freedroid" --exec-prefix=`pwd`"/FreeDroid.app/Contents/MacOS" --bindir=`pwd`"/FreeDroid.app/Contents/MacOS/"
